version: "3.3"
services:
  solr:
    build:
      context: "${SOLR_CONTEXT_FOLDER}"
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/solr/data
    command:
      - solr-precreate
      - plone
      - /plone-config

volumes:
  solr-data: {}
